{{ config(
    pre_hook="ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = true"
) }}

{{ config(
	tags=[var('TAG_DIMENSION')]
) }}


SELECT 
* 
FROM PROD_DB.DBT_PROD.CREDITS
WHERE ROLE IN ('ACTOR','DIRECTOR')
