{{ config(
    pre_hook="ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = true"
) }}

{{ config(
	tags=[var('TAG_DIMENSION')]
) }}
SELECT
ID
,TITLE
,TYPE
,DESCRIPTION
,RELEASE_YEAR
,AGE_CERTIFICATION
,RUNTIME
,GENRES
,PRODUCTION_COUNTRIES
,SEASONS
FROM
-- PROD_DB.DBT_TRANSFORM.TITLES
PROD_DB.DBT_PROD.TITLES
